#!/bin/sh
#
# Starts openbox
#

BIN=/usr/bin/openbox-session
PIDFILE=/var/run/openbox.pid
export DISPLAY=:0

OPENBOX_ARGS=""

start() {
	printf "Starting openbox: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN -- $OPENBOX_ARGS
	[ $? = 0 ] && sleep 3 && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping openbox: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
